### ISSUE TITLE
parameters for MeanTeacher on mini-imagenet

### ISSUE THREAD

**Issue by BrandaAllen** [ahmetius/LP-DeepSSL#3]
What the parameters of MeanTeacher such as "consistency_type, consistency and lr" do you set on mini-imagenet? Appreciated to be told.

**Comment by ahmetius** [comment]
Hi,

You can see the parameters for mini-imagenet here:

https://github.com/ahmetius/LP-DeepSSL/blob/236a4107d4f65606c2bc05a73a03bc44539cdf47/helpers.py#L366

The default values are used for the parameters that are not set above. They can be found here:

https://github.com/ahmetius/LP-DeepSSL/blob/236a4107d4f65606c2bc05a73a03bc44539cdf47/mean_teacher/cli.py#L23

**Comment by BrandaAllen** [comment]
Hi, 
I have gotten some problems when trying to use the mean-teacher model to deal with mini-imagenet dataset(which is a baseline in your paper). 
I use the same dataset, same parameter setting and same architecture of restnet18 with you, but using the original code provided by the authors of mean-teacher. Finally, I got a 0.6338 error rate when using 10000 labeled samples, which is far lower than the results you provided. I think maybe some details have been neglected. Do you have some suggestions?

**Comment by KUN20192022** [comment]
Where is the defination of assert_exactly_one in helper.py,  def create_data_loaders? I couldnot find it, so it is a problem in the processing on my dataset. Appreciated to be told.

**Comment by ahmetius** [comment]
Hello,

it is defined here:

https://github.com/ahmetius/LP-DeepSSL/blob/236a4107d4f65606c2bc05a73a03bc44539cdf47/mean_teacher/utils.py#L40

Clicking on the function call on github shows you the definition of that function.

**Comment by KUN20192022** [comment]
> Hello,
> 
> it is defined here:
> 
> https://github.com/ahmetius/LP-DeepSSL/blob/236a4107d4f65606c2bc05a73a03bc44539cdf47/mean_teacher/utils.py#L40
> 
> Clicking on the function call on github shows you the definition of that function.

OH  thank you very much
